// One-off generator: converts world-atlas's 110m country topojson into flat
// SVG path data keyed by ISO 3166-1 alpha-2, for the stats page's world map.
import { geoNaturalEarth1, geoPath } from "d3-geo";
// @ts-expect-error -- no bundled types, only used here
import { feature } from "topojson-client";
import countries from "i18n-iso-countries";
import en from "i18n-iso-countries/langs/en.json" with { type: "json" };
import worldAtlas from "world-atlas/countries-110m.json" with { type: "json" };
import { writeFileSync } from "node:fs";
import path from "node:path";

countries.registerLocale(en);

const WIDTH = 960;
const HEIGHT = 500;

type TopoFeature = {
	id: string | number;
	properties: { name: string };
	geometry: unknown;
};

const geo = feature(
	worldAtlas as never,
	(worldAtlas as unknown as { objects: { countries: unknown } }).objects
		.countries,
) as unknown as { features: TopoFeature[] };

const projection = geoNaturalEarth1().fitSize([WIDTH, HEIGHT], geo as never);
const pathGen = geoPath(projection);

const entries: { code: string; name: string; d: string }[] = [];
const unmapped: string[] = [];

for (const f of geo.features) {
	const numeric = String(f.id).padStart(3, "0");
	const alpha2 = countries.numericToAlpha2(numeric);
	const d = pathGen(f as never);
	if (!d) continue;
	if (!alpha2) {
		unmapped.push(`${f.id} (${f.properties.name})`);
		continue;
	}
	entries.push({ code: alpha2, name: f.properties.name, d });
}

entries.sort((a, b) => a.code.localeCompare(b.code));

const out = `// GENERATED by src/scripts/dev/generate-world-map-paths.ts — do not hand-edit.
// Natural Earth 110m country outlines (via world-atlas), Natural Earth 1 projection, ${WIDTH}x${HEIGHT} viewBox.
export const WORLD_MAP_VIEWBOX = "0 0 ${WIDTH} ${HEIGHT}" as const;

export type WorldMapCountry = { code: string; name: string; d: string };

export const WORLD_MAP_COUNTRIES: WorldMapCountry[] = ${JSON.stringify(entries)};
`;

const outPath = path.join(
	process.cwd(),
	"src/components/stats/world-map/world-map-paths.generated.ts",
);
writeFileSync(outPath, out);

console.log(`Wrote ${entries.length} country paths to ${outPath}`);
if (unmapped.length) {
	console.log(`Unmapped (skipped): ${unmapped.join(", ")}`);
}
